In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('covid19_global_statistics_2026.csv')

print(df.shape)

(238, 13)

In [3]:
df.head()

,continent,country,population,date,new_cases,active_cases,cases_per_million,total_cases,new_deaths,deaths_per_million,total_deaths,tests_per_million,total_tests
0,Africa,Eritrea,3662244.0,2026-02-16,NaN,0.0,2782.0,10189,NaN,28.0,103.0,6470.0,23693.0
1,Africa,Niger,26083660.0,2026-02-16,NaN,729.0,381.0,9931,NaN,12.0,312.0,9759.0,254538.0
2,Africa,Saint-Helena,6115.0,2026-02-16,NaN,2164.0,354211.0,2166,NaN,NaN,NaN,NaN,NaN
3,South-America,Falkland-Islands,3539.0,2026-02-16,NaN,0.0,545352.0,1930,NaN,NaN,NaN,2439107.0,8632.0
4,North-America,Montserrat,4965.0,2026-02-16,NaN,19.0,282578.0,1403,NaN,1611.0,8.0,3577442.0,17762.0

In [6]:
df.shape

(238, 13)

In [8]:
df.columns

Index(['continent', 'country', 'population', 'date', 'new_cases',
       'active_cases', 'cases_per_million', 'total_cases', 'new_deaths',
       'deaths_per_million', 'total_deaths', 'tests_per_million',
       'total_tests'],
      dtype='str')

In [4]:
df.isna().sum()

continent               2
country                 0
population              9
date                    0
new_cases             221
active_cases           47
cases_per_million       8
total_cases             0
new_deaths            235
deaths_per_million     13
total_deaths            5
tests_per_million      25
total_tests            25
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [9]:
df

,continent,country,population,date,new_cases,active_cases,cases_per_million,total_cases,new_deaths,deaths_per_million,total_deaths,tests_per_million,total_tests
0,Africa,Eritrea,3662244.0,2026-02-16,NaN,0.0,2782.0,10189,NaN,28.0,103.0,6470.0,23693.0
1,Africa,Niger,26083660.0,2026-02-16,NaN,729.0,381.0,9931,NaN,12.0,312.0,9759.0,254538.0
2,Africa,Saint-Helena,6115.0,2026-02-16,NaN,2164.0,354211.0,2166,NaN,NaN,NaN,NaN,NaN
3,South-America,Falkland-Islands,3539.0,2026-02-16,NaN,0.0,545352.0,1930,NaN,NaN,NaN,2439107.0,8632.0
4,North-America,Montserrat,4965.0,2026-02-16,NaN,19.0,282578.0,1403,NaN,1611.0,8.0,3577442.0,17762.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,Europe,UK,68497907.0,2026-02-16,NaN,0.0,363666.0,24910387,NaN,3389.0,232112.0,7628357.0,522526476.0
234,Europe,Russia,145805947.0,2026-02-16,NaN,175641.0,165454.0,24124215,NaN,2762.0,402756.0,1875095.0,273400000.0
235,Asia,Turkey,85561976.0,2026-02-16,NaN,NaN,201399.0,17232066,NaN,1194.0,102174.0,1902052.0,162743369.0
236,Oceania,Australia,26068792.0,2026-02-16,NaN,8716.0,454687.0,11853144,NaN,937.0,24414.0,3142326.0,81916639.0
237,Asia,Vietnam,98953541.0,2026-02-16,NaN,941018.0,117481.0,11625195,NaN,437.0,43206.0,867342.0,85826548.0

In [10]:
data = df.copy()

In [11]:
data

,continent,country,population,date,new_cases,active_cases,cases_per_million,total_cases,new_deaths,deaths_per_million,total_deaths,tests_per_million,total_tests
0,Africa,Eritrea,3662244.0,2026-02-16,NaN,0.0,2782.0,10189,NaN,28.0,103.0,6470.0,23693.0
1,Africa,Niger,26083660.0,2026-02-16,NaN,729.0,381.0,9931,NaN,12.0,312.0,9759.0,254538.0
2,Africa,Saint-Helena,6115.0,2026-02-16,NaN,2164.0,354211.0,2166,NaN,NaN,NaN,NaN,NaN
3,South-America,Falkland-Islands,3539.0,2026-02-16,NaN,0.0,545352.0,1930,NaN,NaN,NaN,2439107.0,8632.0
4,North-America,Montserrat,4965.0,2026-02-16,NaN,19.0,282578.0,1403,NaN,1611.0,8.0,3577442.0,17762.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,Europe,UK,68497907.0,2026-02-16,NaN,0.0,363666.0,24910387,NaN,3389.0,232112.0,7628357.0,522526476.0
234,Europe,Russia,145805947.0,2026-02-16,NaN,175641.0,165454.0,24124215,NaN,2762.0,402756.0,1875095.0,273400000.0
235,Asia,Turkey,85561976.0,2026-02-16,NaN,NaN,201399.0,17232066,NaN,1194.0,102174.0,1902052.0,162743369.0
236,Oceania,Australia,26068792.0,2026-02-16,NaN,8716.0,454687.0,11853144,NaN,937.0,24414.0,3142326.0,81916639.0
237,Asia,Vietnam,98953541.0,2026-02-16,NaN,941018.0,117481.0,11625195,NaN,437.0,43206.0,867342.0,85826548.0

In [12]:
data.duplicated().sum()

np.int64(0)

In [13]:
data = data.drop_duplicates()

In [14]:
data.duplicated().sum()

np.int64(0)

In [15]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   continent           236 non-null    str
 1   country             238 non-null    str
 2   population          229 non-null    float64
 3   date                238 non-null    str
 4   new_cases           17 non-null     float64
 5   active_cases        191 non-null    float64
 6   cases_per_million   230 non-null    float64
 7   total_cases         238 non-null    int64
 8   new_deaths          3 non-null      float64
 9   deaths_per_million  225 non-null    float64
 10  total_deaths        233 non-null    float64
 11  tests_per_million   213 non-null    float64
 12  total_tests         213 non-null    float64
dtypes: float64(9), int64(1), str(3)
memory usage: 24.3 KB

In [16]:
data.isna().sum()

continent               2
country                 0
population              9
date                    0
new_cases             221
active_cases           47
cases_per_million       8
total_cases             0
new_deaths            235
deaths_per_million     13
total_deaths            5
tests_per_million      25
total_tests            25
dtype: int64

In [17]:
data = data.drop(columns='new_cases')

In [18]:
data.head()

,continent,country,population,date,active_cases,cases_per_million,total_cases,new_deaths,deaths_per_million,total_deaths,tests_per_million,total_tests
0,Africa,Eritrea,3662244.0,2026-02-16,0.0,2782.0,10189,NaN,28.0,103.0,6470.0,23693.0
1,Africa,Niger,26083660.0,2026-02-16,729.0,381.0,9931,NaN,12.0,312.0,9759.0,254538.0
2,Africa,Saint-Helena,6115.0,2026-02-16,2164.0,354211.0,2166,NaN,NaN,NaN,NaN,NaN
3,South-America,Falkland-Islands,3539.0,2026-02-16,0.0,545352.0,1930,NaN,NaN,NaN,2439107.0,8632.0
4,North-America,Montserrat,4965.0,2026-02-16,19.0,282578.0,1403,NaN,1611.0,8.0,3577442.0,17762.0

In [19]:
data.count()

continent             236
country               238
population            229
date                  238
active_cases          191
cases_per_million     230
total_cases           238
new_deaths              3
deaths_per_million    225
total_deaths          233
tests_per_million     213
total_tests           213
dtype: int64

In [20]:
data.isna().sum()

continent               2
country                 0
population              9
date                    0
active_cases           47
cases_per_million       8
total_cases             0
new_deaths            235
deaths_per_million     13
total_deaths            5
tests_per_million      25
total_tests            25
dtype: int64